version: "3.9"

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
        environment:
            - NODE_ENV=development
        command: sh -c "cd react-app && yarn start"
        stdin_open: true
